package com.example.zoom2u.application.ui.details_base_page.profile

import java.io.Serializable

class ProfileResponce (

    var FirstName: String?,
    var LastName: String? ,
    var Email: String? ,
    var Mobile: String? ,
    var Company: String?  ,
    var DisplayName: String?
    // var type: String? ,
    //var customerId: String? ,
    /*var deviceId: String? ,
    var createdDateTime: String? ,
    var modifiedDateTime: String? ,
    var timezone: String? ,
    var countryCode: String? ,
    var photo: String?,
    var ewayId: Int? ,
    var company: String? ,
    var isTemandoRetailer: Boolean? ,
    var active: Boolean? ,
    var accountType: String? ,
    var deviceType: String? ,
    var campaignId: Int? ,
    var braintreeId: Any? ,
    var type: String? ,
    var planId: Int? ,
    var disabledDateTime: Any? ,
    var disabledReason: Any? ,
    var paymentMethod: String? ,
    var zoom2uApiKey: Any? ,
    var courier: Any? ,
    var statusChangeWebhookUrl: Any? ,
    var customerApiKey: Any? ,
    var trackingUrl: Any? ,
    var suppressReceiverNotifications: Boolean? ,
    var isNewCustomer: Boolean? ,
    var leadId: Int? ,
    var salesPerson: Any?,
    var accountsEmail: String? ,
    var paymentTermsDays: Any? ,
    var isApiTestMode: Boolean? ,
    var pricingPlanTemplateId: Any? ,
    var banner: Any? ,
    var bannerEnabled: Boolean? ,
    var includeToImportantNotifications: Boolean?,
    var isRateUsEmailSent: Boolean? ,
    var title: Any? ,
    var role: Any? ,
    var buyingBehaviour: Any? ,
    var emailOptions: Any?,
    var loyaltyOptions: Any? ,
    var phoneNumber: Any?,
    var industryType: Any? ,
    var customerSize: Any? ,
    var isDropIdCheckRequired: Any? ,
    var showATLInTracking: Boolean? ,
    var autoChargePaymentMethodId: Any? ,
    var accountContactName: String?,
    var accountContactPhone: String? ,
    var hasRequestedCouriersWithBackgroundCheck: Boolean? ,
    var runEligibility: Any? ,
    var doesAlcoholDeliveries: Boolean? ,
    var runPricingTemplateId: Any? ,
    var fraudStatus: Any? ,
   // var address: Address? ,
    var preferredCouriers: Any? ,
    var accountingContactId: Any? ,
    var parentCustomerId: Any? ,
    var parentCustomerBehaviour: Any? ,
    var howDidYouFindUs: String?,
    var deliveryRequests: List<Any>? ,
    var preferredLocations: List<Any>? ,
    var attachedCouriers: List<Any>? ,
    var quotes: List<Any>? ,
    var paymentMethods: List<Any>? ,
    var invoice: List<Any>? ,
    var pricingPlan: Any? ,
    var pricingPlanHistories: List<Any>? ,
    var extraLargeQuoteRequests: List<Any>? ,
    var deliveryRunBatchQuotes: List<Any>?,
    var pricingPlanTemplate: Any? ,
    var heavyFreightQuoteRequests: List<Any>? ,
    var adjustments: List<Any>? ,
    var calls: List<Any>? ,
    var customerShippingProfiles: List<Any>? ,
    var runImportQueueEntries: List<Any>? ,
    var runPricingPlanTemplate: Any?,
    var parent: Any? ,
    var children: Any? ,
    var displayName: String? ,*/
): Serializable