package com.zoom2u_customer.ui.application.bottom_navigation.profile

import android.os.Parcelable
import kotlinx.parcelize.Parcelize


@Parcelize
data class ProfileResponse (
    var `$id`: String? = null,
    var `$type`: String? = null,
    var CustomerId: String? = null,
    var FirstName: String? = null,
    var LastName: String? = null,
    var Email: String? = null,
    var Mobile: String? = null,
    var deviceId: String? = null,
    var CreatedDateTime: String? = null,
    var ModifiedDateTime: String? = null,
    var Timezone: String? = null,
    var CountryCode: String? = null,
    var Photo: String? = null,
    var EwayId: String? = null,
    var Company: String? = null,
    var IsTemandoRetailer: Boolean? = null,
    var Active: Boolean? = null,
    var AccountType: String? = null,
    var DeviceType: String? = null,
    var CampaignId: Int? = null,
    var BraintreeId: String? = null,
    var Type: String? = null,
    var PlanId: Int? = null,
    var DisabledDateTime: String? = null,
    var DisabledReason: String? = null,
    var PaymentMethod: String? = null,
    var Zoom2uApiKey: String? = null,
    var Courier: String? = null,
    var StatusChangeWebhookUrl: String? = null,
    var CustomerApiKey: String? = null,
    var TrackingUrl: String? = null,
    var SuppressReceiverNotifications: Boolean? = null,
    var IsNewCustomer: Boolean? = null,
    var LeadId: Int? = null,
    var SalesPerson: String? = null,
    var AccountsEmail: String? = null,
    var PaymentTermsDays: String? = null,
    var IsApiTestMode: Boolean? = null,
    var PricingPlanTemplateId: String? = null,
    var Banner: String? = null,
    var BannerEnabled: Boolean? = null,
    var IncludeToImportantNotifications: Boolean? = null,
    var IsRateUsEmailSent: Boolean? = null,
    var Title: String? = null,
    var Role: String? = null,
    var BuyingBehaviour: String? = null,
    var EmailOptions: String? = null,
    var LoyaltyOptions: String? = null,
    var PhoneNumber: String? = null,
    var IndustryType: String? = null,
    var CustomerSize: String? = null,
    var IsDropIdCheckRequired: String? = null,
    var ShowATLInTracking: Boolean? = null,
    var AutoChargePaymentMethodId: String? = null,
    var AccountContactName: String? = null,
    var AccountContactPhone: String? = null,
    var HasRequestedCouriersWithBackgroundCheck: Boolean? = null,
    var RunEligibility: String? = null,
    var DoesAlcoholDeliveries: Boolean? = null,
    var RunPricingTemplateId: String? = null,
    var FraudStatus: String? = null,
    var Address: AddressBody? = null,
    var PreferredCouriers: String? = null,
    var AccountingContactId: String? = null,
    var ParentCustomerId: String? = null,
    var ParentCustomerBehaviour: String? = null,
    var HowDidYouFindUs: String? = null,
    var DeliveryRequests: List<String>? = null,
    var PreferredLocations: List<String>? = null,
    var AttachedCouriers: List<String>? = null,
    var Quotes: List<String>? = null,
    var PaymentMethods: List<String>? = null,
    var Invoice: List<String>? = null,
    var PricingPlan: String? = null,
    var PricingPlanHistories: List<String>? = null,
    var ExtraLargeQuoteRequests: List<String>? = null,
    var DeliveryRunBatchQuotes: List<String>? = null,
    var PricingPlanTemplate: String? = null,
    var HeavyFreightQuoteRequests: List<String>? = null,
    var Adjustments: List<String>? = null,
    var Calls: List<String>? = null,
    var CustomerShippingProfiles: List<String>? = null,
    var RunImportQueueEntries: List<String>? = null,
    var RunPricingPlanTemplate: String? = null,
    var Parent: String? = null,
    var Children: String? = null,
    var DisplayName: String? = null,

    ): Parcelable {
    @Parcelize
    data class AddressBody( var `$id`: String? = null,
                        var `$type`: String? = null,
                        var street1: String? = null,
                        var street2: String? = null,
                        var suburb: String? = null,
                        var province: String? = null,
                        var zipcode: String? = null,
                        var location: String? = null): Parcelable


    }



